---
- name: Install common packages
  apt:
    update_cache: yes
    pkg:
      - jq
      - ansible
      - openjdk-8-jdk-headless
      - git
      - git-lfs
      - nvme-cli
      - ntp
      - build-essential
      - wget
      - curl
      - vim
      - screen
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - unzip
      - python3-pip

- name: Initialize git-lfs
  command: git lfs install
  vars:
    ansible_become: no

- name: Install pip packages
  pip:
    executable: pip3
    name:
      - requests
      - PyYaml
      - jinja2

- name: Download awscli
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /home/ubuntu/
    remote_src: yes

- name: Install awscli
  command: /home/ubuntu/aws/install

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"